# Site settings
title: pablin.org
name: pablin.org
author: Pablo Bendersky
email: pablin@pablin.org
description: > # this means to ignore newlines until "baseurl:"
  Pablo Bendersky's blog. I'm a co-founder and developer at Quadion Technologies. I write about
  developing, Apple stuff, and anything that seems interesting to me.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pablin.org" # the base hostname & protocol for your site
twitter_username: pbendersky
github_username:  pbendersky

excerpt_separator: <!-- read more -->

permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown

gems:
  - octopress-genesis-theme
  - octopress-codefence
  - octopress-render-code
  - octopress-feeds